
package com.cxf.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BCertService", targetNamespace = "http://service.cxf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BCertService1 {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertHkbInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertHkbInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertHkbInfo")
    @ResponseWrapper(localName = "GetDetailBcertHkbInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertHkbInfoResponse")
    public String getDetailBcertHkbInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.cxf.service.SzbUser>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetUserListResponse")
    public List<SzbUser> getUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cxf.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertSfzInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertSfzInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertSfzInfo")
    @ResponseWrapper(localName = "GetDetailBcertSfzInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertSfzInfoResponse")
    public String getDetailBcertSfzInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertGSYYZZInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertGSYYZZInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertGSYYZZInfo")
    @ResponseWrapper(localName = "GetDetailBcertGSYYZZInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertGSYYZZInfoResponse")
    public String getDetailBcertGSYYZZInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertJHZ")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertJHZ", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertJHZ")
    @ResponseWrapper(localName = "GetDetailBcertJHZResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertJHZResponse")
    public String getDetailBcertJHZ(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcert70LNZInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcert70LNZInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcert70LNZInfo")
    @ResponseWrapper(localName = "GetDetailBcert70LNZInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcert70LNZInfoResponse")
    public String getDetailBcert70LNZInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcert60LNZInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcert60LNZInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcert60LNZInfo")
    @ResponseWrapper(localName = "GetDetailBcert60LNZInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcert60LNZInfoResponse")
    public String getDetailBcert60LNZInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertLDRKHYZMInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertLDRKHYZMInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertLDRKHYZMInfo")
    @ResponseWrapper(localName = "GetDetailBcertLDRKHYZMInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertLDRKHYZMInfoResponse")
    public String getDetailBcertLDRKHYZMInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertEHSYFWZInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertEHSYFWZInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertEHSYFWZInfo")
    @ResponseWrapper(localName = "GetDetailBcertEHSYFWZInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertEHSYFWZInfoResponse")
    public String getDetailBcertEHSYFWZInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDetailBcertYHSYFWZInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetDetailBcertYHSYFWZInfo", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertYHSYFWZInfo")
    @ResponseWrapper(localName = "GetDetailBcertYHSYFWZInfoResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.service.GetDetailBcertYHSYFWZInfoResponse")
    public String getDetailBcertYHSYFWZInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
