
package com.cxf.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bCertService", targetNamespace = "http://service.cxf.com/", wsdlLocation = "http://222.143.37.13:10016/cxf/bCertService?WSDL")
public class BCertService_Service
    extends Service
{

    private final static URL BCERTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BCERTSERVICE_EXCEPTION;
    private final static QName BCERTSERVICE_QNAME = new QName("http://service.cxf.com/", "bCertService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://222.143.37.13:10016/cxf/bCertService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BCERTSERVICE_WSDL_LOCATION = url;
        BCERTSERVICE_EXCEPTION = e;
    }

    public BCertService_Service() {
        super(__getWsdlLocation(), BCERTSERVICE_QNAME);
    }

    public BCertService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BCERTSERVICE_QNAME, features);
    }

    public BCertService_Service(URL wsdlLocation) {
        super(wsdlLocation, BCERTSERVICE_QNAME);
    }

    public BCertService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BCERTSERVICE_QNAME, features);
    }

    public BCertService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BCertService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BCertService
     */
    @WebEndpoint(name = "BCertServiceImplPort")
    public BCertService1 getBCertServiceImplPort() {
        return super.getPort(new QName("http://service.cxf.com/", "BCertServiceImplPort"), BCertService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BCertService
     */
    @WebEndpoint(name = "BCertServiceImplPort")
    public BCertService1 getBCertServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf.com/", "BCertServiceImplPort"), BCertService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BCERTSERVICE_EXCEPTION!= null) {
            throw BCERTSERVICE_EXCEPTION;
        }
        return BCERTSERVICE_WSDL_LOCATION;
    }

}
